### ISSUE TITLE
Ability to use a custom/different workspace

### ISSUE THREAD

**Issue by davidcollom** [maelvls/clockidup#3]
I use different workspaces to separate personal/work projects etc.

It would be great if I could use / switch workspaces in which I use, via config file or via command line.

Currently looking at: https://github.com/maelvls/clockidup/blob/058ae20c0c929566bb2edb3a4b38ed7d2865ffc0/main.go#L237-L248

It uses the first workspace provided from the API?

**Comment by maelvls** [comment]
Hi! Sorry for the delay 😅

Yes, it picks up the first workspace it finds. When I was writing it, I knew that it was a bad idea and that I should have made it configurable... 😓

I agree, it would be nice to have multiple workspace configurations in the config file, and have some --workspace and maybe ask which default workspace to use during the login command
